name: Docker
on:
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    #tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image for Odoo 12
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./12.0
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            igorvisi/docker-volume-backup:12.0
            igorvisi/docker-volume-backup:12

      - name: Build and push Docker image for Odoo 13
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./13.0
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            igorvisi/docker-volume-backup:13.0
            igorvisi/docker-volume-backup:13

      - name: Build and push Docker image for Odoo 14
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./14.0
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            igorvisi/docker-volume-backup:14.0
            igorvisi/docker-volume-backup:14
            igorvisi/docker-volume-backup:latest